# fly.toml app configuration file generated for glacis on 2024-12-29T14:52:25+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glacis'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
